# Docker profile configuration
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/stockdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: stock-market-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.stockmarket.app.dto,com.stockmarket.app.model

# Disable h2 console in Docker environment
h2:
  console:
    enabled: false

# Kafka topics
kafka:
  topics:
    stock-price-updates: stock-price-updates
    stock-transactions: stock-transactions 